package app

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// userNotesMarker separates ACT-managed content (above) from user-authored
// content (below). Regeneration overwrites everything above the marker and
// preserves everything below. Users who want stable notes put them after it.
const userNotesMarker = "<!-- User notes below this line are preserved by ACT -->"

// renderAgentsMd produces the markdown body for a project's AGENTS.md file.
// Intentionally short — this gets auto-loaded into every Tier 1 and act-agent
// Tier 2 prompt, and also auto-discovered by the claude-code swarm backend.
// Adding 10K tokens here would undo the Phase 3 token diet.
func renderAgentsMd(projectName string, brief *ProjectBrief) string {
	constraints := strings.TrimSpace(brief.Constraints)
	if constraints == "" {
		constraints = "None specified."
	}
	agents := strings.Join(brief.AgentsInvolved, ", ")
	if agents == "" {
		agents = "developer"
	}
	return fmt.Sprintf(`# AGENTS.md

Project context for ACT swarm agents. This file is auto-regenerated by the Planner from the project brief. Edit ACT-managed sections via the `+"`act-agent brief update`"+` conversation, not this file directly. User notes after the preserve marker at the bottom are kept across regenerations.

## Project

**%s**

%s

## Tech stack

%s

## Constraints

%s

## Validation

Assurance (Tier 1 validator) gates task completion at 95%% pass rate via independent tool-based verification. It runs `+"`view`"+`/`+"`grep`"+` against the working directory and does not trust agent-reported evidence. Swarm agents report completion with a brief summary plus file paths — no evidence dumps, no inlined command output, no "proof" blocks.

## Swarm roles on this project

%s

%s
`, projectName, strings.TrimSpace(brief.Description), strings.TrimSpace(brief.TechStack), constraints, agents, userNotesMarker)
}

// writeAgentsMd renders AGENTS.md content from the project brief and writes it
// to <projectDir>/AGENTS.md and a mirrored <projectDir>/CLAUDE.md. The mirror
// exists because claude-code only auto-discovers CLAUDE.md (the agents.md
// cross-vendor spec is not yet natively loaded by claude-code). We copy rather
// than symlink for portability and git-diff simplicity.
//
// If an AGENTS.md already exists and contains the userNotesMarker, content
// after the marker is preserved verbatim and re-appended below the freshly
// rendered ACT-managed section. If the marker is absent (either because the
// file was user-authored or from an older template), the entire existing file
// is treated as user content and appended after the marker — non-destructive.
func writeAgentsMd(projectDir, projectName string, brief *ProjectBrief) error {
	if projectDir == "" {
		return fmt.Errorf("projectDir is empty")
	}
	if brief == nil {
		return fmt.Errorf("brief is nil")
	}

	body := renderAgentsMd(projectName, brief)

	agentsPath := filepath.Join(projectDir, "AGENTS.md")
	if preserved := extractUserNotes(agentsPath); preserved != "" {
		body = body + "\n" + preserved
	}

	if err := os.WriteFile(agentsPath, []byte(body), 0o644); err != nil {
		return fmt.Errorf("write AGENTS.md: %w", err)
	}
	claudePath := filepath.Join(projectDir, "CLAUDE.md")
	if err := os.WriteFile(claudePath, []byte(body), 0o644); err != nil {
		return fmt.Errorf("write CLAUDE.md: %w", err)
	}
	return nil
}

// extractUserNotes returns the user-authored content from an existing
// AGENTS.md file — everything after userNotesMarker if present, otherwise the
// entire file contents (treated as user-authored from a pre-marker version).
// Returns empty string if the file does not exist or cannot be read.
func extractUserNotes(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	content := string(data)
	if idx := strings.Index(content, userNotesMarker); idx != -1 {
		after := content[idx+len(userNotesMarker):]
		return strings.TrimLeft(after, "\n")
	}
	return strings.TrimSpace(content)
}
